title: Horizons - blog de jogos :)
email: tnaires@gmail.com
description: >
  Este é um blog sobre jogos de videogame! Procurarei escrever aqui sobre
  todos os jogos que marcaram minha infância e adolescência, e também
  sobre os que continuam me marcando atualmente.
baseurl: "/horizons"
url: "http://tnaires.github.io"
twitter_username: tnaires
github_username: tnaires
timezone: America/Recife
permalink: /:year/:month/:day/:title/
google_analytics: UA-112014819-1

defaults:
  - scope:
      path: "assets/images/backgrounds"
    values:
      background: true

collections:
  sections:
    output: true

plugins:
  - jekyll-feed
